#!/bin/bash

#Should we go to next step at the end 
continue_cycle=${1}
archPath=$2
echo "Run prep real linking archive $archPath"

# Echo des commandes
ulimit -c 0
ulimit -s unlimited
# Arrete du job des la premiere erreur
#set -e

# URL base for the ECMWF data
BASE_URL="https://forefire.univ-corse.fr/saphir/MARS/20240625"


# List of required files
FILES=(
"cep.FC00Z.06"
"cep.FC00Z.09"
"cep.FC00Z.12"
"cep.FC00Z.15"
"cep.FC00Z.18"
"cep.FC00Z.21"
"cep.FC00Z.24"
)
# Loop through each file and download it if it doesn't exist
for FILE in "${FILES[@]}"; do
    if [ ! -f "$FILE" ]; then
        echo "Downloading $FILE..."
        curl -O "${BASE_URL}/${FILE}" || { echo "Failed to download $FILE"; exit 1; }
    else
        echo "$FILE already exists, skipping download."
    fi
done
#######################################################################
## Rename Files
mv cep.FC00Z.06 cep.FC00Z.M.03
mv cep.FC00Z.09 cep.FC00Z.P.00
mv cep.FC00Z.12 cep.FC00Z.P.03
mv cep.FC00Z.15 cep.FC00Z.P.06
mv cep.FC00Z.18 cep.FC00Z.P.09
mv cep.FC00Z.21 cep.FC00Z.P.12
mv cep.FC00Z.24 cep.FC00Z.P.15
#######################################################################
